### ISSUE TITLE
[Feature] Display Source/Tracker Version+Update Status in the Browse page

### ISSUE THREAD

**Issue by jishnusen** [Suwatte/Suwatte#62]
It is currently difficult to determine whether a source or tracker is out of date relative to the list it was installed from. Although runner's being out of date are indicated by an exclamation, there is no such indication for trackers.

It would be easier for users to track when their sources and trackers are can be updated by surfacing the "update" button, as well as the version number in the "browse" view, which already has a list of all the installed sources and trackers.

**Comment by Mantton** [comment]
Implemented & Fixed in #67
