### ISSUE TITLE
[BUG]: Cannot Migrate all manga from source when runner has been uninstalled.

### ISSUE THREAD

**Issue by ChillDryad** [Suwatte/Suwatte#73]
Example:
`source.a` has 100 followed entries but needs to be migrated to `source.b`. If `source.a` is uninstalled before this migration happens you cannot mass migrate `source.a` to `source.b`. These entries then just sit unable to check for updates or anything without notifying the user.

**Comment by Sterahi** [comment]
Pretty sure this is resolved

**Comment by ChillDryad** [comment]
Pretty sure this has been resolved.
