### ISSUE TITLE
Installed runner settings page view issue

### ISSUE THREAD

**Issue by sinnghabhay80** [Suwatte/Suwatte#88]
Settings here should not come up if there is nothing under it, guessing its just a missing logic error here, attached pics for reference
![image](https://github.com/Suwatte/Suwatte/assets/55084281/fc2b9f67-6be8-4334-a8a0-e83a9a5af67c)![image](https://github.com/Suwatte/Suwatte/assets/55084281/d8b5cfbb-1870-49cb-929b-801aa62faed1)

**Comment by Mantton** [comment]
Fixed in #90
