### ISSUE TITLE
[Feature] OCR using iOS Live Text

### ISSUE THREAD

**Issue by TenEXP** [Suwatte/Suwatte#95]
So far, Panels is the only reader I've seen implement this API, as seen here:

https://guides.panels.app/read-content/live-text

https://developer.apple.com/documentation/visionkit/enabling-live-text-interactions-with-images

**Comment by Mantton** [comment]
At the moment, it's already semi-implemented. Triple Tapping with 2 fingers will trigger Live Text

**Comment by TenEXP** [comment]
Ay nice, closing then. Seperate suggestion though: Maybe advertise it as a feature on the website
